### ISSUE TITLE
blog uses bootstrap for layout

### ISSUE THREAD

**Issue by kjaymiller** [code-newbies/python-thursday-blog#10]
<b>Phillip</b> added the card <a href="http://ift.tt/1WVSPq6">blog uses bootstrap for layout</a> to the <b>Issues</b> list in the <b>PTBlog</b> board at August 27, 2015 at 07:21PM<br><br><br><br><a href="http://ift.tt/1WVSPq6">View on Trello</a>

**Comment by degustaf** [comment]
Resolved by PR #26
